[project]
name = "core"
version = "0.1.0"
description = ""
authors = [
    {name = "Sultan",email = "sultan@gmail.com"}
]
requires-python = ">=3.12"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"