# Stage 1: Build stage (includes Python packages installation)
FROM python:3.11-slim AS builder

# Set environment variables to improve runtime behavior
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

# Set the working directory inside the builder container
WORKDIR /app

# Copy only requirements for efficient caching
COPY requirements.txt .
RUN apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    libssl-dev \
    libffi-dev \
    && rm -rf /var/lib/apt/lists/*

# Upgrade pip and install aiohttp
RUN pip install --upgrade pip setuptools wheel \
    && pip install --no-cache-dir -r requirements.txt
# Install Python dependencies

# Copy the application code to the builder
COPY . .

# Stage 2: Runtime stage (lightweight image)
FROM python:3.11-slim

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

# Set the working directory inside the runtime container
WORKDIR /app

# Copy only the necessary files from the builder stage
COPY --from=builder /usr/local/lib/python3.11 /usr/local/lib/python3.11
COPY --from=builder /app /app

# Command to run your application
# CMD ["python"," /app/telegram_bot/aiogram_run.py"]
# CMD ["ls", "-la", "/app/telegram_bot"]
EXPOSE 8000

CMD ["python", "/app/api.py"]